# ~/.config/starship/starship.toml


format="""
$all\
$line_break\
$conda\
$directory\
$status\
$character"""
add_newline = true # Inserts a blank line between shell prompts
scan_timeout = 20
command_timeout = 1000

[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 20%
threshold = 20
style = "bold red"
discharging_symbol = "💀 "

[[battery.display]]  # "bold yellow" style and 💦 symbol when capacity is between 20% and 40%
threshold = 40
style = "bold yellow"
discharging_symbol = "💦 "
charging_symbol = "⚡️ "

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold yellow)"

[conda]
format = '[\($environment\)]($style) '
style = "bold green"
ignore_base = false

[directory]
truncation_length = 5
truncation_symbol = ".../"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = ""

[git_status]
format = '([\[$ahead_behind$all_status\]]($style) )'
conflicted = "="
ahead = "⇡${ahead_count}"
behind = "⇣${behind_count}"
diverged = "⇕${ahead_count}:${behind_count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
style = "bold blue"

[nodejs]
format = "via [🤖 $version]($style) "

[status]
disabled = false

[username]
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = false
format =  " ~(bold) [$hostname]($style) "
style =   "bold green"
disabled = false
